name: Lint

on:
  push:
    branches:
      [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version-file: .golangci-lint-version

      - name: Run golangci-lint (integration tests)
        uses: golangci/golangci-lint-action@v9
        with:
          version-file: .golangci-lint-version
          args: --build-tags integration ./test/integration/...
